version: '3.8'

services:
  spark-master:
    build:
      context: . # S'assurer que le point est bien présent
      dockerfile: ./docker/Dockerfile
    image: my-spark-image
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/app/data

  spark-worker:
    image: my-spark-image
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/app/data

  spark-app:
    image: my-spark-image
    container_name: spark-app
    depends_on:
      - spark-master
    command: "spark-submit --class CCFDataFrame --master spark://spark-master:7077 /app/graph_scala_2.12-1.0.jar"
    volumes:
      - ./data:/app/data